var SPIRITUAL_QUOTES = [
  // SRI RAMAKRISHNA
  {text:"As many faiths, so many paths.", author:"Sri Ramakrishna"},
  {text:"God is in all men, but all men are not in God; that is why we suffer.", author:"Sri Ramakrishna"},
  {text:"When the flower blooms, the bees come uninvited.", author:"Sri Ramakrishna"},
  {text:"The winds of grace blow all the time. All we need to do is set our sails.", author:"Sri Ramakrishna"},
  {text:"Do not seek illumination unless you seek it as a man whose hair is on fire seeks a pond.", author:"Sri Ramakrishna"},
  {text:"You see many stars in the sky at night, but not when the sun rises. Can you therefore say that there are no stars in the heavens during the day?", author:"Sri Ramakrishna"},
  {text:"The fabled musk deer searches the world over for the source of the scent which comes from within.", author:"Sri Ramakrishna"},
  {text:"Travel in all the four quarters of the earth, yet you will find nothing anywhere. Whatever there is, is only here.", author:"Sri Ramakrishna"},
  {text:"Unalloyed love of God is the essential thing. All else is unreal.", author:"Sri Ramakrishna"},
  {text:"One must be very particular about telling the truth. Through truth one can realize God.", author:"Sri Ramakrishna"},
  {text:"Disease is the tax which the soul pays for the body, as the tenant pays house-rent for the use of the house.", author:"Sri Ramakrishna"},
  {text:"Knowledge leads to unity, but ignorance to diversity.", author:"Sri Ramakrishna"},
  {text:"God can be realized through all paths. All religions are true.", author:"Sri Ramakrishna"},
  {text:"To work without attachment is to work without the expectation of reward or fear of any punishment in this world or the next.", author:"Sri Ramakrishna"},
  {text:"The world is indeed a mixture of truth and make-believe. Discard the make-believe and take the truth.", author:"Sri Ramakrishna"},
  {text:"Bondage is of the mind; freedom too is of the mind.", author:"Sri Ramakrishna"},
  {text:"If you must be mad, be it not for the things of the world. Be mad with the love of God.", author:"Sri Ramakrishna"},
  {text:"Many are the names of God and infinite the forms through which He may be approached.", author:"Sri Ramakrishna"},
  {text:"When the divine vision is attained, all appear equal; and there remains no distinction of good and bad, or of high and low.", author:"Sri Ramakrishna"},
  {text:"It is easy to talk on religion, but difficult to practice it.", author:"Sri Ramakrishna"},
  {text:"God is everywhere but He is most manifest in man. So serve man as God. That is as good as worshipping God.", author:"Sri Ramakrishna"},
  {text:"The sun can give heat and light to the whole world, but he cannot do so when the clouds shut out his rays. Similarly, as long as egotism veils the heart, God cannot shine upon it.", author:"Sri Ramakrishna"},
  {text:"Lovers of God do not belong to any caste.", author:"Sri Ramakrishna"},
  {text:"Unless one always speaks the truth, one cannot find God Who is the soul of truth.", author:"Sri Ramakrishna"},
  {text:"More are the names of God and infinite are the forms through which He may be approached. In whatever name and form you worship Him, through them you will realize Him.", author:"Sri Ramakrishna"},
  {text:"Common men talk bagfuls of religion but do not practice even a grain of it. The wise man speaks a little, even though his whole life is religion expressed in action.", author:"Sri Ramakrishna"},
  {text:"Pray to God that your attachment to the world may become less and less, and your love for God may become more and more.", author:"Sri Ramakrishna"},
  {text:"Through selfless work, love of God grows in the heart.", author:"Sri Ramakrishna"},
  {text:"What you need is to feel the necessity for God. When you feel that longing, you will find Him.", author:"Sri Ramakrishna"},
  {text:"The goal of life is to realize God. Love Him. Merge in Him.", author:"Sri Ramakrishna"},
  {text:"A man is truly free, even here in this embodied state, if he knows that God is the true agent and he by himself is powerless to do anything.", author:"Sri Ramakrishna"},
  {text:"Finish the few duties you have at hand, and then you will have peace.", author:"Sri Ramakrishna"},
  {text:"One cannot have the vision of God as long as one has these three: shame, hatred, and fear.", author:"Sri Ramakrishna"},

  // SWAMI VIVEKANANDA
  {text:"Arise, awake, and stop not till the goal is reached.", author:"Swami Vivekananda"},
  {text:"The world is the great gymnasium where we come to make ourselves strong.", author:"Swami Vivekananda"},
  {text:"In a conflict between the heart and the brain, follow your heart.", author:"Swami Vivekananda"},
  {text:"You cannot believe in God until you believe in yourself.", author:"Swami Vivekananda"},
  {text:"Talk to yourself once in a day, otherwise you may miss meeting an excellent person in this world.", author:"Swami Vivekananda"},
  {text:"The greatest religion is to be true to your own nature. Have faith in yourselves.", author:"Swami Vivekananda"},
  {text:"Strength is Life, Weakness is Death.", author:"Swami Vivekananda"},
  {text:"All the powers in the universe are already ours. It is we who have put our hands before our eyes and cry that it is dark.", author:"Swami Vivekananda"},
  {text:"We are what our thoughts have made us; so take care about what you think.", author:"Swami Vivekananda"},
  {text:"The great secret of true success, of true happiness, is this: the man or woman who asks for no return, the perfectly unselfish person, is the most successful.", author:"Swami Vivekananda"},
  {text:"Take up one idea. Make that one idea your life — think of it, dream of it, live on that idea.", author:"Swami Vivekananda"},
  {text:"Condemn none: if you can stretch out a helping hand, do so. If you cannot, fold your hands, bless your brothers, and let them go their own way.", author:"Swami Vivekananda"},
  {text:"In a day, when you don't come across any problems, you can be sure that you are travelling in a wrong path.", author:"Swami Vivekananda"},
  {text:"They alone live, who live for others.", author:"Swami Vivekananda"},
  {text:"Truth can be stated in a thousand different ways, yet each one can be true.", author:"Swami Vivekananda"},
  {text:"The moment I have realized God sitting in the temple of every human body, the moment I stand in reverence before every human being and see God in him — that moment I am free.", author:"Swami Vivekananda"},
  {text:"Do not be afraid of a small beginning. Great things come afterwards. Be courageous.", author:"Swami Vivekananda"},
  {text:"Neither seek nor avoid, take what comes.", author:"Swami Vivekananda"},
  {text:"Be not afraid of anything. You will do marvellous work.", author:"Swami Vivekananda"},
  {text:"Education is the manifestation of the perfection already in man.", author:"Swami Vivekananda"},
  {text:"The fire that warms us can also consume us; it is not the fault of the fire.", author:"Swami Vivekananda"},
  {text:"Purity, patience, and perseverance are the three essentials to success, and above all, love.", author:"Swami Vivekananda"},
  {text:"Have faith in yourselves, great convictions are the mothers of great deeds.", author:"Swami Vivekananda"},
  {text:"Fill the brain with high thoughts, highest ideals, place them day and night before you, and out of that will come great work.", author:"Swami Vivekananda"},
  {text:"Who is helping you, don't forget them. Who is loving you, don't hate them. Who is believing you, don't cheat them.", author:"Swami Vivekananda"},
  {text:"All differences in this world are of degree, and not of kind, because oneness is the secret of everything.", author:"Swami Vivekananda"},
  {text:"Where can we go to find God if we cannot see Him in our own hearts and in every living being?", author:"Swami Vivekananda"},
  {text:"Do one thing at a time, and while doing it put your whole soul into it to the exclusion of all else.", author:"Swami Vivekananda"},
  {text:"Comfort is no test of truth. Truth is often far from being comfortable.", author:"Swami Vivekananda"},
  {text:"Stand up, be bold, be strong. Take the whole responsibility on your own shoulders.", author:"Swami Vivekananda"},
  {text:"The greatest sin is to think yourself weak.", author:"Swami Vivekananda"},
  {text:"He who sees Shiva in the poor, in the weak and the diseased, really worships Shiva.", author:"Swami Vivekananda"},
  {text:"Learn everything that is good from others, but bring it in, and in your own way absorb it; do not become others.", author:"Swami Vivekananda"},
  {text:"All power is within you; you can do anything and everything.", author:"Swami Vivekananda"},
  {text:"Each work has to pass through these stages — ridicule, opposition, and then acceptance.", author:"Swami Vivekananda"},

  // SRI SARADA DEVI
  {text:"If you want peace, do not find fault with others. Rather see your own faults.", author:"Sri Sarada Devi"},
  {text:"No one is a stranger, my child; the whole world is your own.", author:"Sri Sarada Devi"},
  {text:"I tell you one thing — if you want peace of mind, do not find fault with others.", author:"Sri Sarada Devi"},
  {text:"As you smell the fragrance of a flower by handling it, so you learn to pray by praying.", author:"Sri Sarada Devi"},
  {text:"One must be patient like the earth. What iniquities are being perpetrated on her! Yet she quietly endures them all.", author:"Sri Sarada Devi"},
  {text:"The purpose of one's life is to realize God. Love Him. Feel His presence.", author:"Sri Sarada Devi"},
  {text:"Even the impossible becomes possible through devotion.", author:"Sri Sarada Devi"},
  {text:"Ordinary human love results in misery. Love for God brings blessedness.", author:"Sri Sarada Devi"},
  {text:"I am the mother of the wicked, as I am the mother of the virtuous. Never fear. Whenever you are in distress, say to yourself, I have a mother.", author:"Sri Sarada Devi"},
  {text:"The Master used to say that if one could weep for God, one would not have to practice any other spiritual discipline.", author:"Sri Sarada Devi"},
  {text:"Don't be afraid. Human birth is full of suffering and one has to endure everything patiently, taking the name of God.", author:"Sri Sarada Devi"},
  {text:"Everything will come in time. The teacher has infinite patience.", author:"Sri Sarada Devi"},
  {text:"Let me tell you how to love all equally. Do not demand anything of those you love.", author:"Sri Sarada Devi"},
  {text:"One must live carefully. Every action produces its results. It is not good to use harsh words towards others or to be responsible for their suffering.", author:"Sri Sarada Devi"},
  {text:"Is faith so cheap, my child? Faith is the last thing to come. Hold on to it.", author:"Sri Sarada Devi"},
  {text:"The whole world is your own. No one is a stranger. Everyone is your very own.", author:"Sri Sarada Devi"},
  {text:"Practise meditation and gradually you will feel that unspeakable joy. God alone is real, all else is false.", author:"Sri Sarada Devi"},
  {text:"If you practice spiritual disciplines for some time in a solitary place, you will find that your mind has become strong.", author:"Sri Sarada Devi"},
  {text:"My son, the Master (Sri Ramakrishna) had a maternal attitude towards everyone. He has left me behind to manifest that Divine Motherhood.", author:"Sri Sarada Devi"},
  {text:"Pray to God with a longing heart. He will surely listen to you.", author:"Sri Sarada Devi"},
  {text:"The mind is everything. It is in the mind alone that one feels pure and impure.", author:"Sri Sarada Devi"},
  {text:"Through selfless work, love of God grows in the heart. Then through His grace one realizes Him in course of time.", author:"Sri Sarada Devi"},
  {text:"Always remember, the grace of God is always upon you. Never be afraid.", author:"Sri Sarada Devi"}
];